<?php
ob_start();
// grades/export_pdf.php
// Exports one student's grade report as a PDF using FPDF.

require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../config/session.php';
require_once __DIR__ . '/../lib/fpdf.php';
requireLogin();

$id = intval($_GET['id'] ?? 0);
if (!$id) {
    header('Location: /edutrack/students/view.php');
    exit;
}

$conn = getConnection();

// ── Fetch student ─────────────────────────────
$stmt = $conn->prepare("SELECT * FROM students WHERE id = ? LIMIT 1");
$stmt->bind_param('i', $id);
$stmt->execute();
$student = $stmt->get_result()->fetch_assoc();
if (!$student) {
    header('Location: /edutrack/students/view.php');
    exit;
}

// ── Fetch grades ──────────────────────────────
$stmt2 = $conn->prepare("
    SELECT g.grade, s.subject_code, s.subject_name
    FROM grades g
    JOIN subjects s ON s.id = g.subject_id
    WHERE g.student_id = ?
    ORDER BY s.subject_name
");
$stmt2->bind_param('i', $id);
$stmt2->execute();
$gradesResult = $stmt2->get_result();
$grades = [];
while ($row = $gradesResult->fetch_assoc()) {
    $grades[] = $row;
}

// ── Compute average ───────────────────────────
$avgStmt = $conn->prepare("SELECT AVG(grade) AS avg FROM grades WHERE student_id = ?");
$avgStmt->bind_param('i', $id);
$avgStmt->execute();
$average = $avgStmt->get_result()->fetch_assoc()['avg'];
$conn->close();

// ── Remarks helper ────────────────────────────
function remarks(float $g): string {
    if ($g >= 96) return 'Excellent';
    if ($g >= 90) return 'Very Good';
    if ($g >= 85) return 'Good';
    if ($g >= 80) return 'Satisfactory';
    if ($g >= 75) return 'Passing';
    return 'Failed';
}

function statusColor(float $g): array {
    if ($g >= 85) return [56, 217, 169];   // green
    if ($g >= 75) return [245, 166, 35];   // amber
    return [255, 95, 109];                  // red
}

// ── Build PDF ─────────────────────────────────
class GradeReportPDF extends FPDF {
    private string $studentName;
    private string $schoolName = 'BATSTATEU';

    public function __construct(string $name) {
        parent::__construct();
        $this->studentName = $name;
    }

    public function Header(): void {
        // Dark header bar
        $this->SetFillColor(13, 15, 20);
        $this->Rect(0, 0, 210, 28, 'F');

        // Accent stripe
        $this->SetFillColor(91, 141, 255);
        $this->Rect(0, 28, 210, 2, 'F');

        // School name
        $this->SetFont('Arial', 'B', 9);
        $this->SetTextColor(139, 147, 168);
        $this->SetXY(10, 8);
        $this->Cell(0, 5, strtoupper($this->schoolName), 0, 1, 'L');

        // Title
        $this->SetFont('Arial', 'B', 15);
        $this->SetTextColor(232, 236, 245);
        $this->SetXY(10, 14);
        $this->Cell(0, 7, 'STUDENT GRADE REPORT', 0, 1, 'L');

        // EduTrack brand (right side)
        $this->SetFont('Arial', 'B', 11);
        $this->SetTextColor(91, 141, 255);
        $this->SetXY(-50, 10);
        $this->Cell(40, 7, 'EduTrack', 0, 0, 'R');

        $this->SetY(36);
    }

    public function Footer(): void {
        $this->SetY(-14);
        $this->SetFillColor(19, 22, 30);
        $this->Rect(0, $this->GetY(), 210, 20, 'F');

        $this->SetFont('Arial', '', 7.5);
        $this->SetTextColor(85, 94, 116);
        $this->SetXY(10, $this->GetY() + 4);
        $this->Cell(0, 4,
            'Generated by EduTrack  |  ' . $this->schoolName . '  |  ' . date('F d, Y \a\t g:i A'),
            0, 0, 'L'
        );
        $this->SetXY(-40, $this->GetY());
        $this->Cell(30, 4, 'Page ' . $this->PageNo(), 0, 0, 'R');
    }
}

$fullName = $student['firstname'] . ' ' . $student['lastname'];
$pdf = new GradeReportPDF($fullName);
$pdf->SetMargins(12, 10, 12);
$pdf->SetAutoPageBreak(true, 20);
$pdf->AddPage();
$pdf->SetTextColor(30, 30, 30);

// ── Student Info Card ─────────────────────────
$pdf->SetFillColor(19, 22, 30);
$pdf->SetDrawColor(37, 42, 56);
$pdf->Rect(12, 38, 186, 38, 'DF');

// Left column labels
$pdf->SetFont('Arial', '', 7.5);
$pdf->SetTextColor(85, 94, 116);
$pdf->SetXY(18, 44);
$pdf->Cell(40, 5, 'STUDENT NAME', 0);
$pdf->SetXY(18, 55);
$pdf->Cell(40, 5, 'STUDENT ID', 0);

$pdf->SetXY(100, 44);
$pdf->Cell(40, 5, 'COURSE', 0);
$pdf->SetXY(100, 55);
$pdf->Cell(40, 5, 'YEAR LEVEL', 0);

// Left column values
$pdf->SetFont('Arial', 'B', 10);
$pdf->SetTextColor(232, 236, 245);
$pdf->SetXY(18, 49);
$pdf->Cell(75, 5, $fullName);
$pdf->SetFont('Arial', '', 9);
$pdf->SetXY(18, 60);
$pdf->Cell(75, 5, $student['student_id']);

$pdf->SetFont('Arial', 'B', 9);
$pdf->SetXY(100, 49);
$pdf->Cell(75, 5, $student['course']);
$pdf->SetFont('Arial', '', 9);
$pdf->SetXY(100, 60);
$pdf->Cell(75, 5, $student['year_level']);

// ── Average badge (top right of card) ─────────
if ($average !== null) {
    [$r, $g, $b] = statusColor((float)$average);
    $pdf->SetFillColor($r, $g, $b);
    $pdf->SetDrawColor($r, $g, $b);
    // Soft badge bg (10% opacity simulation: blend toward dark bg)
    $pdf->SetFillColor(
        (int)(19 + ($r - 19) * 0.15),
        (int)(22 + ($g - 22) * 0.15),
        (int)(30 + ($b - 30) * 0.15)
    );
    $pdf->Rect(155, 43, 37, 28, 'DF');

    $pdf->SetFont('Arial', 'B', 16);
    $pdf->SetTextColor($r, $g, $b);
    $pdf->SetXY(155, 46);
    $pdf->Cell(37, 8, number_format((float)$average, 2), 0, 1, 'C');

    $pdf->SetFont('Arial', 'B', 7);
    $pdf->SetXY(155, 56);
    $pdf->Cell(37, 5, strtoupper(remarks((float)$average)), 0, 1, 'C');
}

// ── Grades Table ──────────────────────────────
$y = 84;
$pdf->SetY($y);

// Table header
$pdf->SetFillColor(26, 30, 42);
$pdf->SetDrawColor(37, 42, 56);
$pdf->SetFont('Arial', 'B', 7.5);
$pdf->SetTextColor(85, 94, 116);
$pdf->SetLineWidth(0.1);

$pdf->SetXY(12, $y);
$pdf->SetFillColor(26, 30, 42);
$pdf->Cell(22, 8, 'CODE', 1, 0, 'L', true);
$pdf->Cell(90, 8, 'SUBJECT', 1, 0, 'L', true);
$pdf->Cell(28, 8, 'GRADE', 1, 0, 'C', true);
$pdf->Cell(48, 8, 'REMARKS', 1, 1, 'C', true);

// Table rows
$pdf->SetFont('Arial', '', 9);
$pdf->SetDrawColor(37, 42, 56);

$rowColors = [
    [19, 22, 30],
    [22, 26, 36],
];

if (empty($grades)) {
    $pdf->SetFillColor(19, 22, 30);
    $pdf->SetTextColor(85, 94, 116);
    $pdf->SetXY(12, $pdf->GetY());
    $pdf->Cell(188, 10, 'No grades recorded.', 1, 1, 'C', true);
} else {
    foreach ($grades as $i => $g) {
        [$fr, $fg, $fb] = $rowColors[$i % 2];
        $pdf->SetFillColor($fr, $fg, $fb);

        $gradeVal = (float)$g['grade'];
        [$cr, $cg, $cb] = statusColor($gradeVal);

        $rowY = $pdf->GetY();
        $pdf->SetXY(12, $rowY);

        // Code cell
        $pdf->SetTextColor(139, 147, 168);
        $pdf->Cell(22, 9, $g['subject_code'], 1, 0, 'L', true);

        // Subject cell
        $pdf->SetTextColor(232, 236, 245);
        $pdf->Cell(90, 9, $g['subject_name'], 1, 0, 'L', true);

        // Grade cell — colored
        $pdf->SetTextColor($cr, $cg, $cb);
        $pdf->SetFont('Arial', 'B', 9);
        $pdf->Cell(28, 9, number_format($gradeVal, 2), 1, 0, 'C', true);
        $pdf->SetFont('Arial', '', 9);

        // Remarks cell
        $pdf->SetTextColor($cr, $cg, $cb);
        $pdf->Cell(48, 9, remarks($gradeVal), 1, 1, 'C', true);
    }

    // ── Average row ───────────────────────────
    $pdf->SetFillColor(13, 15, 20);
    $pdf->SetFont('Arial', 'B', 9);
    [$cr, $cg, $cb] = statusColor((float)$average);

    $pdf->SetXY(12, $pdf->GetY());
    $pdf->SetTextColor(139, 147, 168);
    $pdf->Cell(112, 9, 'OVERALL AVERAGE', 1, 0, 'R', true);
    $pdf->SetTextColor($cr, $cg, $cb);
    $pdf->Cell(28, 9, number_format((float)$average, 2), 1, 0, 'C', true);
    $pdf->Cell(48, 9, strtoupper(remarks((float)$average)), 1, 1, 'C', true);
}

// ── Grading Scale legend ──────────────────────
$legendY = $pdf->GetY() + 10;
$pdf->SetFillColor(19, 22, 30);
$pdf->SetDrawColor(37, 42, 56);
$pdf->SetLineWidth(0.1);
$pdf->Rect(12, $legendY, 186, 26, 'DF');

$pdf->SetFont('Arial', 'B', 7);
$pdf->SetTextColor(85, 94, 116);
$pdf->SetXY(18, $legendY + 4);
$pdf->Cell(0, 4, 'GRADING SCALE', 0);

$scale = [
    ['96 - 100', 'Excellent'],
    ['90 - 95',  'Very Good'],
    ['85 - 89',  'Good'],
    ['80 - 84',  'Satisfactory'],
    ['75 - 79',  'Passing'],
    ['Below 75', 'Failed'],
];

$pdf->SetFont('Arial', '', 7.5);
$xPos = 18;
foreach ($scale as $s) {
    $pdf->SetXY($xPos, $legendY + 10);
    $pdf->SetTextColor(139, 147, 168);
    $pdf->Cell(16, 4, $s[0], 0);
    $pdf->SetTextColor(232, 236, 245);
    $pdf->Cell(20, 4, $s[1], 0);
    $xPos += 32;
}

// ── Signature line ────────────────────────────
$sigY = $legendY + 40;
$pdf->SetDrawColor(37, 42, 56);
$pdf->SetLineWidth(0.3);
$pdf->Line(12,  $sigY, 90,  $sigY);
$pdf->Line(120, $sigY, 198, $sigY);

$pdf->SetFont('Arial', '', 7.5);
$pdf->SetTextColor(85, 94, 116);
$pdf->SetXY(12, $sigY + 2);
$pdf->Cell(78, 4, 'Class Adviser / Subject Teacher', 0, 0, 'C');
$pdf->SetXY(120, $sigY + 2);
$pdf->Cell(78, 4, 'Registrar / School Administrator', 0, 0, 'C');

// ── Output ────────────────────────────────────
$filename = 'GradeReport_' . preg_replace('/\s+/', '_', $fullName) . '_' . date('Ymd') . '.pdf';
ob_end_clean();
$pdf->Output('D', $filename);   // 'D' = force download
exit;