<?php
ob_start();
// grades/export_all_pdf.php
// Exports a summary report of ALL students with their averages.
// Admin only.

require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../config/session.php';
require_once __DIR__ . '/../lib/fpdf.php';
requireLogin();

// Optional filter params
$course     = trim($_GET['course']     ?? '');
$year_level = trim($_GET['year_level'] ?? '');

$conn = getConnection();

// ── Fetch students ────────────────────────────
$where  = [];
$params = [];
$types  = '';
if ($course)     { $where[] = 's.course = ?';     $params[] = $course;     $types .= 's'; }
if ($year_level) { $where[] = 's.year_level = ?'; $params[] = $year_level; $types .= 's'; }
$whereSQL = $where ? 'WHERE ' . implode(' AND ', $where) : '';

$sql = "
    SELECT s.*, COALESCE(AVG(g.grade), NULL) AS average, COUNT(g.id) AS subject_count
    FROM students s
    LEFT JOIN grades g ON g.student_id = s.id
    {$whereSQL}
    GROUP BY s.id
    ORDER BY s.lastname, s.firstname
";

if ($params) {
    $stmt = $conn->prepare($sql);
    $stmt->bind_param($types, ...$params);
    $stmt->execute();
    $result = $stmt->get_result();
} else {
    $result = $conn->query($sql);
}

$students = [];
while ($row = $result->fetch_assoc()) {
    $students[] = $row;
}

// Stats
$total   = count($students);
$passing = count(array_filter($students, fn($s) => $s['average'] !== null && $s['average'] >= 75));
$failing = count(array_filter($students, fn($s) => $s['average'] !== null && $s['average'] <  75));
$noGrades= count(array_filter($students, fn($s) => $s['average'] === null));

$conn->close();

function remarks(float $g): string {
    if ($g >= 96) return 'Excellent';
    if ($g >= 90) return 'Very Good';
    if ($g >= 85) return 'Good';
    if ($g >= 80) return 'Satisfactory';
    if ($g >= 75) return 'Passing';
    return 'Failed';
}

// ── PDF ───────────────────────────────────────
class SummaryReportPDF extends FPDF {
    public function Header(): void {
        $this->SetFillColor(13, 15, 20);
        $this->Rect(0, 0, 297, 28, 'F');
        $this->SetFillColor(91, 141, 255);
        $this->Rect(0, 28, 297, 2, 'F');

        $this->SetFont('Arial', 'B', 8);
        $this->SetTextColor(139, 147, 168);
        $this->SetXY(10, 8);
        $this->Cell(0, 5, 'BATSTATEU', 0, 1, 'L');

        $this->SetFont('Arial', 'B', 14);
        $this->SetTextColor(232, 236, 245);
        $this->SetXY(10, 14);
        $this->Cell(0, 7, 'STUDENT GRADES SUMMARY REPORT', 0, 1, 'L');

        $this->SetFont('Arial', 'B', 10);
        $this->SetTextColor(91, 141, 255);
        $this->SetXY(-55, 10);
        $this->Cell(45, 7, 'EduTrack', 0, 0, 'R');

        $this->SetY(36);
    }

    public function Footer(): void {
        $this->SetY(-14);
        $this->SetFillColor(19, 22, 30);
        $this->Rect(0, $this->GetY(), 297, 20, 'F');
        $this->SetFont('Arial', '', 7);
        $this->SetTextColor(85, 94, 116);
        $this->SetXY(10, $this->GetY() + 4);
        $this->Cell(0, 4,
            'Generated by EduTrack  |   BATSTATEU  |  ' . date('F d, Y \a\t g:i A'),
            0, 0, 'L');
        $this->SetXY(-40, $this->GetY());
        $this->Cell(30, 4, 'Page ' . $this->PageNo(), 0, 0, 'R');
    }
}

$pdf = new SummaryReportPDF('L', 'mm', 'A4');  // Landscape for more columns
$pdf->SetMargins(10, 10, 10);
$pdf->SetAutoPageBreak(true, 18);
$pdf->AddPage();

// ── Filter info ───────────────────────────────
$pdf->SetFont('Arial', '', 8);
$pdf->SetTextColor(139, 147, 168);
$pdf->SetXY(10, 38);
$filterLabel = 'All Students';
if ($course && $year_level) $filterLabel = "{$course}  ·  {$year_level}";
elseif ($course)     $filterLabel = $course;
elseif ($year_level) $filterLabel = $year_level;
$pdf->Cell(0, 5, 'Filter: ' . $filterLabel . '   |   Generated: ' . date('F d, Y'));

// ── Stat cards ────────────────────────────────
$statsY = 46;
$cards = [
    ['Total Students', $total,    [91, 141, 255]],
    ['Passing (≥75)',  $passing,  [56, 217, 169]],
    ['Failing (<75)',  $failing,  [255, 95, 109]],
    ['No Grades',      $noGrades, [85, 94, 116]],
];
$cardW = 60; $cardX = 10;
foreach ($cards as [$label, $val, [$r,$g,$b]]) {
    $pdf->SetFillColor(19, 22, 30);
    $pdf->SetDrawColor($r, $g, $b);
    $pdf->SetLineWidth(0.4);
    $pdf->Rect($cardX, $statsY, $cardW - 2, 20, 'DF');

    $pdf->SetFont('Arial', '', 7);
    $pdf->SetTextColor(85, 94, 116);
    $pdf->SetXY($cardX + 3, $statsY + 3);
    $pdf->Cell($cardW - 8, 4, strtoupper($label));

    $pdf->SetFont('Arial', 'B', 16);
    $pdf->SetTextColor($r, $g, $b);
    $pdf->SetXY($cardX + 3, $statsY + 8);
    $pdf->Cell($cardW - 8, 8, (string)$val);

    $cardX += $cardW;
}

// ── Table ─────────────────────────────────────
$tableY = $statsY + 27;
$pdf->SetY($tableY);

// Header row
$cols = [
    ['#',          8,  'C'],
    ['Student ID', 28, 'L'],
    ['Full Name',  58, 'L'],
    ['Course',     55, 'L'],
    ['Year',       20, 'C'],
    ['Subjects',   20, 'C'],
    ['Average',    22, 'C'],
    ['Status',     30, 'C'],
    ['Remarks',    36, 'C'],
];

$pdf->SetFillColor(26, 30, 42);
$pdf->SetDrawColor(37, 42, 56);
$pdf->SetLineWidth(0.1);
$pdf->SetFont('Arial', 'B', 7);
$pdf->SetTextColor(85, 94, 116);
$pdf->SetXY(10, $tableY);
foreach ($cols as [$hdr, $w, $align]) {
    $pdf->Cell($w, 8, $hdr, 1, 0, $align, true);
}
$pdf->Ln();

// Data rows
$rowBg = [[19,22,30],[22,26,36]];
foreach ($students as $i => $s) {
    [$fr,$fg,$fb] = $rowBg[$i % 2];
    $pdf->SetFillColor($fr, $fg, $fb);

    $avg = $s['average'] !== null ? (float)$s['average'] : null;
    $statusLabel = $avg === null ? '—' : ($avg >= 75 ? 'Passing' : 'Failing');
    $remarksLabel = $avg !== null ? remarks($avg) : '—';

    if ($avg !== null) {
        [$cr,$cg,$cb] = $avg >= 85 ? [56,217,169] : ($avg >= 75 ? [245,166,35] : [255,95,109]);
    }

    $rowY = $pdf->GetY();
    $pdf->SetXY(10, $rowY);

    // #
    $pdf->SetTextColor(85, 94, 116);
    $pdf->SetFont('Arial', '', 7.5);
    $pdf->Cell(8, 8, $i + 1, 1, 0, 'C', true);

    // Student ID
    $pdf->SetTextColor(139, 147, 168);
    $pdf->Cell(28, 8, $s['student_id'], 1, 0, 'L', true);

    // Name
    $pdf->SetTextColor(232, 236, 245);
    $pdf->SetFont('Arial', 'B', 7.5);
    $pdf->Cell(58, 8, $s['lastname'] . ', ' . $s['firstname'], 1, 0, 'L', true);

    // Course
    $pdf->SetFont('Arial', '', 7);
    $pdf->SetTextColor(232, 236, 245);
    $pdf->Cell(55, 8, $s['course'], 1, 0, 'L', true);

    // Year
    $pdf->SetTextColor(139, 147, 168);
    $pdf->Cell(20, 8, $s['year_level'], 1, 0, 'C', true);

    // Subjects
    $pdf->Cell(20, 8, $s['subject_count'], 1, 0, 'C', true);

    // Average
    $pdf->SetFont('Arial', 'B', 8);
    if ($avg !== null) {
        $pdf->SetTextColor($cr, $cg, $cb);
        $pdf->Cell(22, 8, number_format($avg, 2), 1, 0, 'C', true);
        $pdf->Cell(30, 8, $statusLabel, 1, 0, 'C', true);
        $pdf->Cell(36, 8, $remarksLabel, 1, 1, 'C', true);
    } else {
        $pdf->SetTextColor(85, 94, 116);
        $pdf->Cell(22, 8, '—', 1, 0, 'C', true);
        $pdf->Cell(30, 8, 'No Grades', 1, 0, 'C', true);
        $pdf->Cell(36, 8, '—', 1, 1, 'C', true);
    }
}

$filename = 'EduTrack_GradesSummary_' . date('Ymd_His') . '.pdf';
ob_end_clean();
$pdf->Output('D', $filename);
exit;